// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MobileNavbarController from "./mobile_navbar_controller.js"
application.register("mobile-navbar", MobileNavbarController)

import ProjectSubscriptionController from "./project_subscription_controller.js"
application.register("project-subscription", ProjectSubscriptionController)


// const btn = document.querySelector('.fa-house');

// btn.addEventListener('click', function onClick() {
//   btn.style.backgroundColor = 'salmon';
// });
