meta_product_name: "Contio"
meta_title: "Contio - Making Project Management Easy"
meta_description: "Contio is a project management app specifically for contractors, making projects simpler one task at a time. Download the app today to start enjoying our features."
meta_image: "cover.png" # should exist in `app/assets/images/`
